// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type LookupType struct {
	ID          uuid.UUID      `json:"id"`
	Key         string         `json:"key"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type LookupValue struct {
	ID        uuid.UUID             `json:"id"`
	TypeID    uuid.UUID             `json:"type_id"`
	Code      string                `json:"code"`
	Name      string                `json:"name"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	IsActive  sql.NullBool          `json:"is_active"`
	CreatedAt sql.NullTime          `json:"created_at"`
}
