// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getLookupValues = `-- name: GetLookupValues :many
SELECT lv.id, lv.code, lv.name, lv.metadata
FROM lookup_values lv
JOIN lookup_types lt ON lv.type_id = lt.id
WHERE lt.key = $1 AND lv.is_active = TRUE
`

type GetLookupValuesRow struct {
	ID       uuid.UUID             `json:"id"`
	Code     string                `json:"code"`
	Name     string                `json:"name"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) GetLookupValues(ctx context.Context, key string) ([]GetLookupValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLookupValues, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLookupValuesRow
	for rows.Next() {
		var i GetLookupValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
